'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DE_shifts() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("DE_shifts"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("DE_shifts") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property HQ_shifts() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("HQ_shifts"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("HQ_shifts") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DE_shifts_names() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("DE_shifts_names"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("DE_shifts_names") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property HQ_shifts_names() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("HQ_shifts_names"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("HQ_shifts_names") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DE_departments() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("DE_departments"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("DE_departments") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property HQ_departments() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("HQ_departments"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("HQ_departments") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DE_departments_names() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("DE_departments_names"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("DE_departments_names") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property HQ_departments_names() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("HQ_departments_names"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("HQ_departments_names") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DE_departments_bundesland() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("DE_departments_bundesland"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("DE_departments_bundesland") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property HQ_departments_bundesland() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("HQ_departments_bundesland"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("HQ_departments_bundesland") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DE_shifts_surcharges() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("DE_shifts_surcharges"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("DE_shifts_surcharges") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property HQ_shifts_surcharges() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("HQ_shifts_surcharges"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("HQ_shifts_surcharges") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DE_shifts_overtime() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("DE_shifts_overtime"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("DE_shifts_overtime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property HQ_shifts_overtime() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("HQ_shifts_overtime"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("HQ_shifts_overtime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DE_shifts_sick_paid() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("DE_shifts_sick_paid"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("DE_shifts_sick_paid") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property HQ_shifts_sick_paid() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("HQ_shifts_sick_paid"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("HQ_shifts_sick_paid") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DE_shifts_sick_surcharges() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("DE_shifts_sick_surcharges"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("DE_shifts_sick_surcharges") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property HQ_shifts_sick_surcharges() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("HQ_shifts_sick_surcharges"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("HQ_shifts_sick_surcharges") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.PLANDAY.My.MySettings
            Get
                Return Global.PLANDAY.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
